let a = 5;
const b = 10;
const c = '2';

console.log('Arithmetic Operations. Same type:');
console.log(a + b);
console.log(a - b);
console.log(a * b);
console.log(b / a);
console.log(b % a);
console.log(a ** b);
console.log('Arithmetic Operations. Different type:');
console.log(a + c);
console.log(b - c);
console.log(a * c);
console.log(b / c);
console.log(b % c);
console.log(a ** c);
console.log('Arithmetic Operations. Miscellaneous:');
console.log(++a);
console.log(--a);
console.log(a += b);
console.log(a -= b);
console.log(a *= b);
console.log(a /= b);
a = b;
console.log(a);
a = c;
console.log(c);
